os: Visual Studio 2015
version: "{build}"
build: off
skip_tags: true

environment:
  matrix:
    - arch: x86_64
      bits: 64
      nodejs_version: 10
    - arch: i686
      bits: 32
      nodejs_version: 10

platform:
  - x64
  # - x86

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm -g i npm@latest
  - npm i --ignore-scripts
  - for /f %%i in ('node -v') do set exact_nodejs_version=%%i
  - npm run build
  # - npm run test || travis_terminate 1
  - npm run deploy

#on_success:
# - for %%i in (prebuilds\*) do appveyor PushArtifact %%i
