name: Publish
on:
  workflow_dispatch:
  release:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64]
        include:
          - os: windows-latest
            arch: i686
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{matrix.arch}})
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 14

      - name: Setup Linux Dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
          sudo apt-get update -qq
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update -qq
          sudo apt-get install -y software-properties-common gcc-5 g++-5 libx11-dev libxtst-dev libxt-dev libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev xorg-dev libxcb-xkb-dev libxkbfile-dev libxinerama-dev
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5

      - name: Install Packages
        run: npm i --ignore-scripts

      - name: Build & Publish Prebuilds
        run: npm run build:ci -- --msvs_version=2019
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          ARCH: ${{ matrix.arch }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish NPM Package
        if: startsWith(matrix.os, 'ubuntu')
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
